Uber image
solo-io/bumblebee pull request #58
Opened 2022-01-11 21:05 UTC by lgadban

2022-01-13 08:02 UTC, Akasurde commented on docs/concepts.md
> +You can also build an "uber" image which contains the `bee` CLI in addition to your BPF programs. The end result is a standard docker image which can be distributed via standard docker-like workflows
```suggestion
BumbleBee by default uses a containerized build environment to build your BPF programs to an ELF file, then packages that in an OCI image according to our image spec.

You can also build an "uber" image that contains the `bee` CLI in addition to your BPF programs. The end result is a standard docker image that can be distributed via standard docker-like workflows to run your BPF program anywhere that can run containers, such as a K8s cluster. Note that you will need sufficient capabilities to run the image, as loading and running the BPF program is a privileged operation for most intents and purposes.
```

2022-01-13 19:48 UTC, EItanya commented on docs/concepts.md
> +Again, this will have a better UX very soon!
Don't mention this, it just highlights potential issues

2022-01-13 19:53 UTC, EItanya commented on pkg/cli/internal/commands/build/build.go
> +	UberImage string
Do we need a separate arg for `UberImage` vs `BuildImage`

2022-01-13 19:54 UTC, EItanya commented on bee/Dockerfile-bee
> +FROM alpine:3.14
Any reason not to just call this `Dockerfile`? There's only one in this directory

2022-01-14 03:26 UTC, lgadban commented on docs/concepts.md
> +Again, this will have a better UX very soon!
I opted to document it as it's a pretty bad UX bug. Basically if someone runs the packaged image interactively with docker, their terminal basically becomes unusable, unless they follow the steps documented here.

Kinda treating this as a known-issue/FAQ since I'm not sure where else I would document it. Additionally, this will only be a problem until I can get https://github.com/solo-io/bumblebee/issues/29 fixed, which I am almost finished working on in another branch.

2022-01-14 03:29 UTC, lgadban commented on pkg/cli/internal/commands/build/build.go
> +	UberImage string
Currently we do; the `BuildImage` allows for an override of the builder image (i.e. the one that contains `clang`, `vmlinux` etc.) and the `UberImage` is which image to use as a base image for packing up the full image

2022-01-14 03:30 UTC, lgadban commented on bee/Dockerfile-bee
> +FROM alpine:3.14
Purely for being explicit to its purpose as well ease of finding it since there are other `Dockerfiles` in the repo.

Happy to change it, what do you think?

2022-01-14 14:08 UTC, EItanya commented on pkg/cli/internal/commands/build/build.go
> +	UberImage string
Ahhh ok I see my confusion here. I think we should use the 2nd arg here which was the registry ref for the bee image. There's no need to push the image to that registry if we are packaging it in the docker image. Does that make sense?

2022-01-14 14:24 UTC, lgadban commented on pkg/cli/internal/commands/build/build.go
> +	UberImage string
Sorry, I completely misspoke!

`BeeImage` is the image which contains the `bee` CLI and is used as the base image for the packaged docker image. This defaults to the official solo one we will publish via CI. Users would only need to override it if they didn't want to use our image for some reason (or use a different hub, etc.)

`UberImage` is the image and tag of the fully built & packaged docker image, i.e. the end result of the build.

2022-01-14 19:20 UTC, EItanya requested changes

2022-01-14 19:20 UTC, EItanya commented on pkg/cli/internal/commands/packageCmd/package.go
> +package packageCmd
nit: should be named `package` just like the rest of the `cmd` packages

2022-01-14 19:23 UTC, lgadban commented on pkg/cli/internal/commands/packageCmd/package.go
> +package packageCmd
I agree! but it can't be because `package` is a reserved word; `package package`

2022-01-14 19:38 UTC, EItanya commented on pkg/cli/internal/commands/packageCmd/package.go
> +package packageCmd
ahhhh lol

2022-01-14 19:39 UTC, EItanya commented on pkg/cli/internal/commands/packageCmd/package.go
> +package packageCmd
Then `package_cmd`, and have the dir named `package`?

2022-01-14 19:49 UTC, EItanya approved these changes

2022-01-14 19:49 UTC, merged