Add additional options for build and run
solo-io/bumblebee pull request #89
Opened 2022-07-20 22:46 UTC by SirNexus

Create additional options for build and run to allow for more custom use cases, as well as export WatchMaps to allow use cases where external packages want to use it as a dependency.

2022-07-22 15:17 UTC, SirNexus commented on pkg/loader/loader.go
> +			case ebpf.SchedCLS:
This is no longer needed for my own functionality (using a custom loader), so happy to remove unless we want to also support these types of programs.

2022-07-25 17:31 UTC, SirNexus commented on pkg/loader/loader.go
> +	WatchMaps(ctx context.Context, watchedMaps map[string]WatchedMap, coll map[string]*ebpf.Map, watcher MapWatcher) error
Right, I don't necessarily want to watch these maps right after load. Really, this would make more sense if bumblebee also called Load and then Watch independently.

2022-07-25 17:33 UTC, SirNexus commented on pkg/loader/loader.go
> +		os.Mkdir(path, perm)
This currently assumes the user is supplying a path pointing to a `bpf` type filesystem. I think it would make sense to add that to the help string. An error will be naturally generated when the programs attempt to pin to a non-`bpf` filesystem, but we can fail early by adding a check here. What do you think?

2022-07-25 20:18 UTC, lgadban commented on pkg/loader/loader.go
> +		os.Mkdir(path, perm)
Ahh ok, so the use-case is passing something like `/sys/fs/bpf/bee/` to create or a preexisting `/sys/fs/bpf` etc.

In that case, might be nice to update the help text but I don't know if it's even necessary, whatever you think.

Also, I think allowing the underlying error to be returned if used improperly is fine, no need to re-implement a fs type check here.

2022-07-25 20:21 UTC, lgadban commented on pkg/loader/loader.go
> +	WatchMaps(ctx context.Context, watchedMaps map[string]WatchedMap, coll map[string]*ebpf.Map, watcher MapWatcher) error
We went back and forth on this design a bit. If this is needed for our other components, I think this change is fine.

Does the change in interface doesn't impact the `bee` loader/runner other than what changes were made in this PR? Basically we are a little light on testing so if you could just do a sanity check that `bee` is running correctly after this change that would be much appreciated

2022-07-25 22:58 UTC, SirNexus commented on pkg/loader/loader.go
> +		os.Mkdir(path, perm)
Good catch, I think it makes sense to return the error on os.Mkdir as well :+1:

2022-07-26 14:29 UTC, SirNexus commented on pkg/loader/loader.go
> +	WatchMaps(ctx context.Context, watchedMaps map[string]WatchedMap, coll map[string]*ebpf.Map, watcher MapWatcher) error
Checked! Everything runs well.

2022-07-26 14:29 UTC, SirNexus commented on pkg/loader/loader.go
> +			case ebpf.SchedCLS:
I agree with that. Will remove.

2022-07-27 01:39 UTC, lgadban requested changes
just 1 thing (i think) to change but looks great otherwise!

2022-07-27 01:39 UTC, lgadban commented on pkg/loader/loader.go
> +		if prog.Type == ebpf.UnspecifiedProgram {
just out of curiosity did you run into a situation where this check was needed?

2022-07-27 12:26 UTC, EItanya reviewed
LGTM overall

2022-07-27 16:02 UTC, SirNexus commented on pkg/loader/loader.go
> +		if prog.Type == ebpf.UnspecifiedProgram {
I did! When running a BPF program that doesn't specify a `SEC` according to https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/lib/bpf/libbpf.c#n9002, it will silently fail to load the program. This line ensures there's at least a debug log for a user to figure out why their program isn't being included.

2022-07-27 16:14 UTC, SirNexus commented on pkg/cli/internal/commands/build/build.go
> +		fmt.Sprintf("CFLAGS=%s", strings.Join(opts.CFlags, " ")),
Shouldn't:
```
CFLAGS= ~/bumblebee/builder/build.sh tcpconnect.c tcpconnect.o
+ CFLAGS=
+ clang-13 -g -O2 -target bpf -D__TARGET_ARCH_x86 -Wall -c tcpconnect.c -o tcpconnect.o
+ llvm-strip-13 -g tcpconnect.o
```

2022-07-29 17:33 UTC, lgadban requested changes

2022-07-29 17:37 UTC, lgadban approved these changes
LGTM

2022-07-29 17:37 UTC, merged